//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<double> Mileage { get; set; }
        public string Fuel_type { get; set; }
        public string Transmission { get; set; }
    
        public virtual User User { get; set; }
    }
}
